Allow "Semesters to Show" field to be temporarily blank
ScottyLabs/course-tool pull request #77
Opened 2022-10-30 05:32 UTC by Lhwhatever

Should fix #76.

This allows backspacing to work as a user might expect; i.e. they can clear the field and enter a new value. If the user leaves the field blank and unfocuses the field, it will revert back to its last valid value.

This was more complicated to implement than expected. An auxiliary state has to be implemented to handle the case when the field is temporarily blank (a future developer may be able to address this). This auxiliary state updates the global state (i.e. calls the dispatch function) through a useEffect hook.

In addition, due to the limitations of the input[type=number] element, we need to add a onKeyPress handler to disable key presses for non-numeric keys, as the onChange handler cannot detect when non-numeric input is given to the field.

# Description

Closes #76 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:

- Node.js version: 18.9.0
- Desktop/Mobile: Desktop
- OS: Linux 5.19.0 (EndeavourOS)
- Browser: Firefox 105.0.1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-30 19:42 UTC, btwj requested changes
Some comments on the current behavior and refactoring.

2022-10-30 19:42 UTC, btwj commented on frontend/src/components/Aggregate.tsx
> +const numeric = /\d/;
For consistency, name this `numericRegex` too.

2022-10-30 19:42 UTC, btwj commented on frontend/src/components/Aggregate.tsx
> +
I don't think there's a way to get around needing an auxiliary state, so this is fine. You might be able to streamline it though: the input has `numSemsField`. Once the input is unfocused, we either restore to the redux state if its value is nonnumeric, or update the redux state if its value is a valid number.

That way, we don't need to override the keyDown event. I tested it locally and currently, there are some odd behaviors where after backspacing, I can't type any numbers anymore. I think the above method would be more robust.

2022-10-30 19:42 UTC, btwj commented on frontend/src/components/Aggregate.tsx
>            />
Also, could you refactor the numSems input out as another component in the same file? The logic is getting a bit complicated.

2022-10-31 04:09 UTC, Lhwhatever reviewed
Resolved in 810383e24f03043268c416e0a53592bf1408cab8 and cbd4e45219a2ac7b201fbe55bfdb721f38757973

2022-11-12 19:38 UTC, merged