Allow omission of hyphen when searching by course ID in ScheduleSearch
ScottyLabs/course-tool pull request #78
Opened 2022-10-30 18:41 UTC by Lhwhatever

# Description

This allows you to omit the hyphen when searching by course ID while adding courses to your schedule.

Closes #74 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

**Test Configuration**:

- Node.js version: 18.9.0
- Desktop/Mobile: Desktop
- OS: Linux 5.19.0 (EndeavourOS)
- Browser: Firefox 105.0.1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-30 22:48 UTC, btwj requested changes

2022-10-30 22:48 UTC, btwj commented on frontend/src/components/Aggregate.tsx
>          <div className="flex flex-row justify-between text-sm">
I think you branched off your previous feature branch, these changes don't belong in this PR.

2022-10-30 22:50 UTC, btwj requested changes

2022-10-30 22:50 UTC, btwj commented on frontend/src/components/ScheduleSearch.tsx
>          selectedItems.map(({ courseID }) => courseID).indexOf(course.courseID) <
This works, but it would be faster to hyphenate inputValue if necessary and then check only on inputValue.

2022-10-31 03:05 UTC, closed without merging

2022-10-31 03:22 UTC, Lhwhatever commented
Replaced by GH-79 (simpler implementation, and with irrelevant changes removed.)