Upgraded nextjs and fixed virtualizer bug
ScottyLabs/course-tool pull request #96
Opened 2022-12-03 21:24 UTC by Icyviolet23

# Description

Upgraded Nextjs to version 13.0.6
Upgraded React to version 18.2.0
Upgraded React-dom to version 18.2.0
Upgraded react-virtual to version 3.0.0-beta.26

Closes #[REPLACE WITH ISSUE NUMBER]

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I manually tested on the course tool and it seems to work lol. I fixed the list scrolling bug and the virtualizer works

**Test Configuration**:

- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-12-05 17:56 UTC, Lhwhatever requested changes

2022-12-05 17:56 UTC, Lhwhatever commented on frontend/.vscode/settings.json
> +{
personal project settings should not be in the commit

2022-12-05 17:56 UTC, Lhwhatever commented on frontend/src/components/ScheduleSearch.tsx
> +  const rowVirtualizer = useVirtualizer({
seems to work

2023-01-21 20:35 UTC, Lhwhatever approved these changes
LGTM

2023-01-21 20:36 UTC, merged

2023-01-28 19:30 UTC, Nicolapps commented
Awesome, thanks!